[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "DwGLWi4HVytijLWPgbogFxj3JDtRRTP1AYA5KyeTDT9z"

[registry]
url = "https://api.apr.dev"

[provider]
# Read cluster and wallet from environment variables if set, fallback to existing values
cluster = "${ANCHOR_CLUSTER}"
wallet = "${ANCHOR_WALLET}"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
